Renaming movement user association
GridtNetwork/gridtlib pull request #20
Opened 2023-01-13 23:14 UTC by JoepoFloepo

2023-01-15 20:51 UTC, AntoninThioux commented
Everything is fine. No renames missing or anything. I would just remove the unused imports: `from gridt.models import UserToUserLink` in user and movement tests

2023-01-15 21:00 UTC, AntoninThioux requested changes
Everything is fine. No renames missing or anything. I would just remove the unused imports: `from gridt.models import UserToUserLink` in user and movement tests

2023-01-16 16:21 UTC, Drvanon commented
This is going to be a great improvement!

2023-01-19 20:50 UTC, AntoninThioux approved these changes

2023-01-19 20:50 UTC, merged